name: innim_remote_error
description: Remote error object and common codes for Innim projects. Using Dio.
version: 0.4.2
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_remote_error
issue_tracker: https://github.com/Innim/flutter_remote_error/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.5.0
  dio: ^5.0.0
  equatable: ^2.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.1
  innim_lint: ^0.3.1
  json_serializable: ^4.1.1
  test: ^1.17.2
