name: innim_remote_error
description: Remote error object and common codes for Innim projects.
version: 0.1.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_remote_error
issue_tracker: https://github.com/Innim/flutter_remote_error/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.7
  equatable: ^1.2.2
  async: ^2.4.2
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  test: ^1.14.2
